"""add_user_id_to_game_session

Revision ID: 81472fd55b61
Revises: b8cf99b6d8b5
Create Date: 2026-02-11 17:03:48.730082

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "81472fd55b61"
down_revision: Union[str, None] = "b8cf99b6d8b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column as nullable first
    op.add_column(
        "game_sessions", sa.Column("user_id", sa.UUID(), nullable=True)
    )

    # 2. Backfill data from characters table
    op.execute(
        """
        UPDATE game_sessions
        SET user_id = characters.user_id
        FROM characters
        WHERE game_sessions.character_id = characters.id
        """
    )
    
    # 3. Alter column to not null
    op.alter_column("game_sessions", "user_id", nullable=False)

    # 4. Create constraints
    op.create_index(
        op.f("ix_game_sessions_user_id"),
        "game_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "game_sessions", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "game_sessions", type_="foreignkey")
    op.drop_index(op.f("ix_game_sessions_user_id"), table_name="game_sessions")
    op.drop_column("game_sessions", "user_id")
    # ### end Alembic commands ###
