"""add turn count and ending fields

Revision ID: 88a8666d7a92
Revises: 64c17718eabe
Create Date: 2026-02-03 00:26:03.793204

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "88a8666d7a92"
down_revision: Union[str, None] = "64c17718eabe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game_sessions", sa.Column("turn_count", sa.Integer(), nullable=False)
    )
    op.add_column(
        "game_sessions",
        sa.Column("ending_type", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "scenarios", sa.Column("max_turns", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scenarios", "max_turns")
    op.drop_column("game_sessions", "ending_type")
    op.drop_column("game_sessions", "turn_count")
    # ### end Alembic commands ###
