"""add max_turns to game_sessions

Revision ID: 9611f102b9c8
Revises: 88a8666d7a92
Create Date: 2026-02-03 02:11:23.678490

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9611f102b9c8"
down_revision: Union[str, None] = "88a8666d7a92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game_sessions", sa.Column("max_turns", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game_sessions", "max_turns")
    # ### end Alembic commands ###
