"""add genre and difficulty to scenarios

Revision ID: 963de0b90109
Revises: 9611f102b9c8
Create Date: 2026-02-03 02:21:08.276833

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "963de0b90109"
down_revision: Union[str, None] = "9611f102b9c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scenarios", sa.Column("genre", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "scenarios",
        sa.Column("difficulty", sa.String(length=20), nullable=False),
    )
    op.create_index(
        op.f("ix_scenarios_difficulty"),
        "scenarios",
        ["difficulty"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scenarios_genre"), "scenarios", ["genre"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scenarios_genre"), table_name="scenarios")
    op.drop_index(op.f("ix_scenarios_difficulty"), table_name="scenarios")
    op.drop_column("scenarios", "difficulty")
    op.drop_column("scenarios", "genre")
    # ### end Alembic commands ###
