"""add_scenario_id_to_characters

Revision ID: b72081227ac8
Revises: 07306584053f
Create Date: 2026-02-06 12:00:55.707293

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b72081227ac8"
down_revision: Union[str, None] = "07306584053f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "characters", sa.Column("scenario_id", sa.UUID(), nullable=False)
    )
    op.create_index(
        op.f("ix_characters_scenario_id"),
        "characters",
        ["scenario_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "characters", "scenarios", ["scenario_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "characters", type_="foreignkey")
    op.drop_index(op.f("ix_characters_scenario_id"), table_name="characters")
    op.drop_column("characters", "scenario_id")
    # ### end Alembic commands ###
