"""Add image_url to game_messages

Revision ID: b8cf99b6d8b5
Revises: b72081227ac8
Create Date: 2026-02-09 15:30:55.347845

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8cf99b6d8b5"
down_revision: Union[str, None] = "b72081227ac8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game_messages",
        sa.Column("image_url", sa.String(length=500), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game_messages", "image_url")
    # ### end Alembic commands ###
